### ISSUE TITLE
anticheat test

### ISSUE THREAD

**Issue by srwgin** [Xelloss-HC/Inazuma-kai#1]

**Comment by Xelloss-HC** [comment]
@srwgin 感谢建议
现在还是半成品并不能实装
而且目前的报告cy似乎会通过结算跳选召唤判断使用挂机

**Comment by Xelloss-HC** [comment]
@srwgin 话说是怎么注意到这东西的

**Comment by srwgin** [comment]
目前上报2个服务器OB GC
任意页面loading完毕后 发OB 主要是4001 这个必发
在进入副本前 最后按OK 和在副本中 每个回合按攻击后 发GC 自带你按OK和攻击的坐标
你可以用fiddler2 只筛选 显示 符合以下4个地址 你就会看到我说的东西
gbf.game.mbga.jp/ob 
game.granbluefantasy.jp/ob 
gbf.game.mbga.jp/gc 
game.granbluefantasy.jp/gc

**Comment by Xelloss-HC** [comment]
@srwgin 感谢测试

**Comment by Xelloss-HC** [comment]
@srwgin 检查了一下ob代码有更新

**Comment by srwgin** [comment]
因为我不会解密和解混淆 只看过老版本的解密 只有上面说的那些代码 XD

**Comment by Xelloss-HC** [comment]
@srwgin 看了下新加的部分是针对一些随机值之类的数学方法进行监控的
然后发了4001

**Comment by srwgin** [comment]
那能不能简单说下 如何解混淆和解密呢
谢谢

**Comment by Xelloss-HC** [comment]
@srwgin cy这段混淆其实就是做个字符表利用makeArray做了下转义
